# Generated by Django 4.1.7 on 2023-03-07 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author_post_alter_post_category_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_com',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data comentário'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='email_com',
            field=models.EmailField(max_length=254, verbose_name='E-mail comentário'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name_com',
            field=models.CharField(max_length=50, verbose_name='Nome comentário'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Post comentário'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='published_com',
            field=models.BooleanField(default=False, verbose_name='Publicar comentário?'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário comentário'),
        ),
    ]
