# Generated by Django 4.1.7 on 2023-03-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image_post'),
        ('comentarios', '0002_alter_comments_comment_alter_comments_date_com_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='Post comentário'),
        ),
    ]
